reazdonor/reazdonor/main/routes.py
from reazdonor.models import Donor, Organization, Donations
from flask import Blueprint, render_template, url_for, flash, redirect, request
from reazdonor import mail, db
from flask_mail import Message
from reazdonor.main.forms import ContactForm, DonateForm
from flask_login import current_user
import secrets

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
	data = Organization.query.filter_by(assistance = True).all()
	return render_template('home.html', data=data)

@main.route('/about')
def about():
	return render_template('about.html', title = 'About')

@main.route('/how')
def how():
	return render_template('how.html', title = 'How')

@main.route('/how/signup')
def how_signup():
	return render_template('how_signup.html', title = 'How')

@main.route('/how/login')
def how_login():
	return render_template('how_login.html', title = 'How')

@main.route('/how/search')
def how_search():
	return render_template('how_search.html', title = 'How')

@main.route('/how/donate')
def how_donate():
	return render_template('how_donate.html', title = 'How')

@main.route('/contact', methods = ['GET', 'POST', 'DELETE'])
def contact():
	form = ContactForm()

	if (form.validate_on_submit()):
		body = form.message.data
		email = form.email.data
		Name = form.name.data

		msg = Message(
					'Hello',
					sender = "swe.team6@gmail.com",
					recipients = ['swe.team6@gmail.com']
					)
		msg.body = 'Name: ' + Name + '\nEmail: ' + email + '\n\nMessage: ' + body

		mail.send(msg)
		flash("Your message has been recieved. We will get back to you soon.", 'info')
		return redirect(url_for('main.contact'))

	return render_template('contact.html', title = 'Contact', form = form)

@main.route('/team')
def team():
	return render_template('team.html', title = 'Team')

def send_donation_email(donor, org, amount):
	msg_donor = Message("Donation Reciept", sender = 'swe.team6@gmail.com', recipients = [donor.email])
	msg_org = Message("Donation Recieved", sender = 'swe.team6@gmail', recipients = [org.email])

	msg_donor.body = f'''Hey {donor.first_name} {donor.last_name},

Thanks for donating to {org.organization_name}! They appreciate it.

This is your reciept for your transaction of {amount}
'''
	msg_org.body = f'''Good news {org.organization_name},

You just recieved a donation of {amount}! Thank you for using our site.
'''

	mail.send(msg_donor)
	mail.send(msg_org)

@main.route('/donation_complete')
def donation_complete():
	return render_template('donation_complete.html', title = 'Thank you')

@main.route('/donate/<string:org_id>', methods = ['GET', 'POST'])
def donate(org_id):
	form = DonateForm()

	donor = Donor.query.filter_by(email = current_user.email).first()
	org = Organization.query.get(org_id)

	if (donor is None):
			flash("Please create a donor account to make donations", 'danger')

			return redirect(url_for('main.search'))

	if (form.validate_on_submit()):
		cent = str(form.cent_amount.data)
		if (cent == "" or cent == "0"):
			cent = "00"

		str_amount = "$" + str(form.dollar_amount.data) + "." + cent
		donation = Donations(id = secrets.token_hex(8), amount = str_amount, donor_id = donor.id, org_id = org.id)
		db.session.add(donation)
		db.session.commit()

		send_donation_email(donor, org, str_amount)
		return redirect(url_for('main.donation_complete'))

	return render_template('donate.html', title = 'Donate', form = form)

@main.route('/search', methods=['GET', 'POST'])
def search():
    if request.method == "POST":
        search_string = request.form['orgns']
        
        data = Organization.query.filter(Organization.organization_name.like('%' + search_string + '%')).all()
        # all in the search box will return all the tuples
        if len(data) == 0 and search_string == 'all': 
            data = Organization.query.all()
        return render_template('search.html', data = data)
    return render_template('search.html', title = 'Search For Orgs')

@main.route('/organization/<string:org_id>')
def organization(org_id):
	org = Organization.query.get_or_404(org_id)

	return render_template('org_home.html', title = org.organization_name, org = org)

reazdonor/reazdonor/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, current_app
from reazdonor import db, bcrypt, mail
from reazdonor.users.forms import SignUpForm, LoginForm, RequestResetForm, PasswordResetForm, UpdateOrgAccountForm, UpdateDonorAccountForm, UpdatePasswordForm
from reazdonor.models import Donor, Organization, Donations
from flask_login import login_user, current_user, logout_user
from flask_mail import Message
import secrets
import os
from PIL import Image

users = Blueprint('users', __name__)

@users.route('/login', methods = ['GET', 'POST'])
def login():
	if (current_user.is_authenticated):
		return redirect(url_for('main.home'))
	
	form = LoginForm()

	if (form.validate_on_submit()):
		donor = Donor.query.filter_by(email = form.email.data).first()
		org = Organization.query.filter_by(email = form.email.data).first()

		if (donor and bcrypt.check_password_hash(donor.password, form.password.data)):
			login_user(donor, remember = form.remember_me.data)

			flash("Welcome back!", 'success')
			return redirect(url_for('main.home'))
		elif (org and bcrypt.check_password_hash(org.password, form.password.data)):
			login_user(org, remember = form.remember_me.data)

			flash("Welcome back!", 'success')
			return redirect(url_for('main.home'))
		else:
			flash("Account not found. Please check email and password.", 'danger')

	return render_template('login.html', title = 'Login', form = form)

@users.route('/signup', methods = ['GET', 'POST'])
def signup():
	if (current_user.is_authenticated):
		return redirect(url_for('main.home'))
	
	form = SignUpForm()

	if (form.validate_on_submit()):
		hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

		if (form.member_type.data == 'Donator'):
			donor = Donor(email = form.email.data, password = hashed_pw, first_name = form.first_name.data, last_name = form.last_name.data, city = form.city.data, state = form.state.data)
			db.session.add(donor)
			db.session.commit()

			flash("Account creation was successful. Please login.", 'success')
			return redirect(url_for('users.login'))
		elif (form.member_type.data == 'Organization'):
			org = Organization(email = form.email.data, password = hashed_pw, organization_name = form.organization_name.data, first_name = form.first_name.data, last_name = form.last_name.data, address = form.address.data, address2 = form.address2.data, city = form.city.data, state = form.state.data)
			db.session.add(org)
			db.session.commit()

			flash("Account creation was successful. Please login.", 'success')
			return redirect(url_for('users.login'))

	return render_template('signup.html', title = 'Sign Up', form = form)

@users.route('/logout')
def logout():
	logout_user()

	return redirect(url_for('main.home'))

def send_reset_email(user):
	token = user.get_reset_token()
	msg = Message("Password Reset", sender = 'swe.team6@gmail.com', recipients = [user.email])
	msg.body = f'''Follow this link to reset your password: {url_for('users.reset_token', token = token, _external = True)}
				
Didn't make this request? Feel free to ignore this email.
'''
	mail.send(msg)

@users.route('/reset_password', methods = ['GET', 'POST'])
def request_reset():
	if (current_user.is_authenticated):
		return redirect(url_for('main.home'))

	form = RequestResetForm()

	if (form.validate_on_submit()):
		donor = Donor.query.filter_by(email = form.email.data).first()
		org = Organization.query.filter_by(email = form.email.data).first()

		if (donor is not None):
			send_reset_email(donor)
			flash("Please check your email for a link to reset your password.", 'info')
			return redirect(url_for('users.login'))
		elif (org is not None):
			send_reset_email(org)
			flash("Please check your email for a link to reset your password.", 'info')
			return redirect(url_for('users.login'))

	return render_template('request_reset.html', title = 'Reset Password', form = form)

@users.route('/reset_password/<token>', methods = ['GET', 'POST'])
def reset_token(token):
	if (current_user.is_authenticated):
		return redirect(url_for('main.home'))

	donor = Donor.verify_reset_token(token)
	org = Organization.verify_reset_token(token)

	form = PasswordResetForm()

	if (donor is None and org is not None):
		if (form.validate_on_submit()):
			hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
			org.password = hashed_pw
			db.session.commit()

			flash("Password has been updated. Please login.", 'success')
			return redirect(url_for('users.login'))
	elif (org is None and donor is not None):
		if (form.validate_on_submit()):
			hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
			donor.password = hashed_pw
			db.session.commit()

			flash("Password has been updated. Please login.", 'success')
			return redirect(url_for('users.login'))
	else:
		flash("Invalid or expired token.", 'warning')
		return redirect(url_for('users.request_reset'))

	return render_template('token_reset.html', title = 'Reset Password', form = form)

def save_image(img):
	hex_name = secrets.token_hex(8)
	_, ext = os.path.splitext(img.filename)
	filename = hex_name + ext
	img_path = os.path.join(current_app.root_path, 'static/images/profiles', filename)
	size = (200, 200)
	im = Image.open(img)
	im.thumbnail(size)
	im.save(img_path)

	return filename

@users.route('/org_cp', methods = ['GET', 'POST'])
def org_cp():
	image = url_for('static', filename = 'images/profiles/' + current_user.logo)

	update_account = UpdateOrgAccountForm()
	update_password = UpdatePasswordForm()

	if (update_account.validate_on_submit()):
		if (update_account.logo.data):
			img_file = save_image(update_account.logo.data)
			current_user.logo = img_file

		current_user.first_name = update_account.first_name.data
		current_user.last_name = update_account.last_name.data
		current_user.organization_name = update_account.organization_name.data
		current_user.phone = update_account.phone.data
		current_user.email = update_account.email.data
		current_user.address = update_account.address.data
		current_user.address2 = update_account.address2.data
		current_user.city = update_account.city.data
		current_user.state = update_account.state.data
		current_user.mission = update_account.mission.data
		current_user.impact = update_account.impact.data
		current_user.assistance = update_account.assistance.data
		db.session.commit()

		flash("Account successfully updated.", 'success')
		return redirect(url_for('users.org_cp'))
	elif (request.method == 'GET'):
		update_account.first_name.data = current_user.first_name
		update_account.last_name.data = current_user.last_name
		update_account.organization_name.data = current_user.organization_name
		update_account.phone.data = current_user.phone
		update_account.email.data = current_user.email
		update_account.address.data = current_user.address
		update_account.address2.data = current_user.address2
		update_account.city.data = current_user.city
		update_account.state.data = current_user.state
		update_account.mission.data = current_user.mission
		update_account.impact.data = current_user.impact
		update_account.assistance.data = current_user.impact

	if (update_password.validate_on_submit()):
		if (bcrypt.check_password_hash(current_user.password, update_password.old_password.data)):
			hashed_pw = bcrypt.generate_password_hash(update_password.password.data).decode('utf-8')

			current_user.password = hashed_pw
			db.session.commit()

			flash("Password successfully updated.", 'success')
			return redirect(url_for('users.org_cp'))
		else:
			flash("Unable to update password.", 'danger')
			return redirect(url_for('users.org_cp'))

	return render_template('org_cp.html', title = 'Control Panel', account = update_account, password = update_password, image = image)

@users.route('/donor_cp', methods = ['GET', 'POST'])
def donor_cp():
	image = url_for('static', filename = 'images/profiles/' + current_user.profile_picture)

	update_account = UpdateDonorAccountForm()
	update_password = UpdatePasswordForm()

	if (update_account.validate_on_submit()):
		if (update_account.profile_picture.data):
			img_file = save_image(update_account.profile_picture.data)
			current_user.profile_picture = img_file

		current_user.first_name = update_account.first_name.data
		current_user.last_name = update_account.last_name.data
		current_user.email = update_account.email.data
		current_user.city = update_account.city.data
		current_user.state = update_account.state.data
		current_user.description = update_account.description.data
		db.session.commit()

		flash("Account successfully updated.", 'success')
		return redirect(url_for('users.donor_cp'))
	elif (request.method == 'GET'):
		update_account.first_name.data = current_user.first_name
		update_account.last_name.data = current_user.last_name
		update_account.email.data = current_user.email
		update_account.city.data = current_user.city
		update_account.state.data = current_user.state
		update_account.description.data = current_user.description

	if (update_password.validate_on_submit()):
		if (bcrypt.check_password_hash(current_user.password, update_password.old_password.data)):
			hashed_pw = bcrypt.generate_password_hash(update_password.password.data).decode('utf-8')

			current_user.password = hashed_pw
			db.session.commit()

			flash("Password successfully updated.", 'success')
			return redirect(url_for('users.donor_cp'))
		else:
			flash("Unable to update password.", 'danger')
			return redirect(url_for('users.donor_cp'))

	return render_template('donor_cp.html', title = 'Control Panel', account = update_account, password = update_password, image = image)

@users.route('/load_account')
def load_account():
	org = Organization.query.filter_by(email = current_user.email).first()
	donor = Donor.query.filter_by(email = current_user.email).first()

	if (donor is not None and org is None):
		return redirect(url_for('users.donor_cp'))
	elif (org is not None and donor is None):

reazdonor/reazdonor/templates/about.html
{% extends "layout.html" %}

{% block main %}
	<section>
		<div class="container mt-5">
			<h1 class="display-1">
				<small>
					<u>
						<b>About Us</b>
					</u>
				</small>
			</h1>
			<p class="abttxt lead">
				ReazDonor is a platform for individuals and organizations alike to send and receive donations. It is a place where donors will find organizations to donate and organizations will
				be able to display their profile to accept donations. We simply want to ensure a safe and secure method of receiving funds for inviduals and organizations alike.
			</p>
		</div>
	</section>

	<section class="sect-mv">
		<div class="container">
			<div class="row">
				<div class="col">
					<h1 class="display-4">Mission</h1>
					<p class="abttxt lead">
						Our mission is to make it easy for dononators to find organizations to donate and make the complete donation process easy through our web application.
					</p>
				</div>

				<div class="col">
					<h1 class="display-4">Values</h1>
					<p class="abttxt lead">
						<span>&#9679;</span> Simplicity
					</p>
					<p class="abttxt lead">
						<span>&#9679;</span> Collaboration
					</p>
					<p class="abttxt lead">
						<span>&#9679;</span> Innovation
					</p>
				</div>
			</div>

			<br><br><br>
			<div class="row">
				<h6 class="display-6">Join us today!</h6>
				<div class="container d-flex justify-content-center">
					<a class="btn btn-primary d-lg-inline-block" id="login" href="{{ url_for('users.signup') }}">Sign Up</a>
				</div>	
			</div>
		</div>
	</section>
{% endblock main %}

reazdonor/reazdonor/templates/home.html
{% extends "layout.html" %}

{% block main %}
	<section class="container sect">
		<div>
			<h1 class="display-1">Welcome!</h1>
			<h1 class="display-4">ReazDonor is a place for donors and organizations alike.</h1>
		</div>

		<br><br>

		<div class="emergencybox">
			<p class="lead text-center">These organizations need your attention!</p>
			<p class="lead text-center"> They need immediate assistance.</p>
			<select name="Cars" size="5">
				{% for item in data %}
					<option value="orgname"> {{item.organization_name}} </option>
				{% endfor %}
			</select>
		</div>
	</section>
	
	<section class="container sect">
		<div class="container">
			<div class="row">
				<div class="col">
					<h2>Donors</h2>
					<hr>
					<p class="lead">
						ReazDonor allows you to browse through organizations, so you know exactly what cause your donation is going to.
					</p>
				</div>
				<div class="col">
					<h2>Organizations</h2>
					<hr>
					<p class="lead">
						ReazDonor allows you to broadcast your organization, so donors can find you and learn more about your cause.
					</p>
				</div>
			</div>
			<br><br><br>
			<div class="row">
				<h6 class="display-6">Join us today!</h6>
				<div class="container d-flex justify-content-center">
					<a class="btn btn-primary d-lg-inline-block" id="login" href="{{ url_for('users.signup') }}">Sign Up</a>
				</div>	
			</div>
		</div>
	</section>
{% endblock main %}

reazdonor/reazdonor/templates/how.html
{% extends "layout.html" %}

{% block main %}
	<section>
		<div class="container mt-5">
			<h1 class="display-1">How it Works</h1>
			<br>

			<figure class="text-center">
				<blockquote class="blockquote">
					<p>There is nothing more enthusiastic than donating to organizations that need your help the most.</p>
				</blockquote>

				<figcaption class="blockquote-footer">
					ReazDonor
				</figcaption>
			</figure>
			<br>
		</div>
	</section>

	<section>
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="d-grid gap-2 col-6 mx-auto">
						<a class="btn btn-primary" href="{{ url_for('main.how_signup') }}" role="button">Signup Process</a>
					</div>
					
					<p class="lead mt-2 text-center">
						Signup is a simple process that takes only a little information to access the website. Click the button above to view a video walkthrough
						of how easy it is to sign up and start the donation process.
					</p>
				</div>

				<div class="col-md-4">
					<div class="d-grid gap-2 col-6 mx-auto">
						<a class="btn btn-primary" href="{{ url_for('main.how_login') }}" role="button">Login Process</a>
					</div>
					
					<p class="lead text-center mt-2">
						Logging into your account is easy. It simply requires you to enter your username and password you created to begin the donation process.
						Click the button above to view a video walkthrough of how to login to start the donation process.
					</p>
				</div>

				<div class="col-md-4">
					<div class="d-grid gap-2 col-6 mx-auto">
						<a class="btn btn-primary" href="{{ url_for('main.how_search') }}" role="button">Search Process</a>
					</div>
					
					<p class="lead text-center mt-2">
						We understand that finding organizations are essential. Click the button above to view a video walkthrough so you can
						begin finding the organizations you want to donate to.
					</p>
				</div>
			</div>

			<div class="row justify-content-center mt-5">
				<div class="col-md-4">
					<div class="d-grid gap-2 col-6 mx-auto">
						<a class="btn btn-primary" href="{{ url_for('main.how_donate') }}" role="button">Donation Process</a>
					</div>
					
					<p class="lead text-center mt-2">
						Donating is the last and most essential part of the process. We make sure your donation transaction is smooth and secure.
						Click the button above so you know how to make donations to any organization.
					</p>
				</div>
			</div>
		</div>
	</section>
{% endblock main %}

reazdonor/reazdonor/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="{{ url_for('static', filename = 'stylesheets/ourstyle.css') }}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

		{% if title %}
			<title>{{ title }} - ReazDonor</title>
		{% else %}
			<title>ReazDonor</title>
		{% endif %}
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: tan;">
		<div class="container-fluid">
			<a class="navbar-brand" href="{{ url_for('main.home') }}">
				<img class="logo" src="{{ url_for('static', filename='images/logo.png') }}" alt="logo">
			</a>
			<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
				<div class="navbar-nav">
					<ul class="navbar-nav flex-row flex-wrap bd-navbar-nav pt-2 py-md-0 me-5">
						<li class="nav-item col-6 col-md-auto">
							<a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
						</li>
						<li class="nav-item col-6 col-md-auto">
							<a class="nav-link" href="{{ url_for('main.about') }}">About Us</a>
						</li>
						<li class="nav-item col-6 col-md-auto">
							<a class="nav-link" href="{{ url_for('main.how') }}">How It Works</a>
						</li>
						<li class="nav-item col-6 col-md-auto">
							<a class="nav-link" href="{{ url_for('main.contact') }}">Contact Us</a>
						</li>
						<li class="nav-item col-6 col-md-auto">
							<a class="nav-link" href="{{ url_for('main.team') }}">Team</a>
						</li>
					</ul>

					<form class="d-flex ms-5">
						<a type="button" href="{{ url_for('main.search') }}" class="btn btn-outline-success">Search For Organizations</a>
					</form>

				</div>
			</div>

			{% if current_user.is_authenticated %}
				<a class="nav-link mr-0" id="account" href="{{ url_for('users.load_account') }}">
					<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
						<path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
						<path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
					</svg>
				</a>
			{% endif %}

			{% if current_user.is_authenticated %}
				<a class="btn btn-danger d-lg-inline-block ms-2 me-3" id="logout" href="{{ url_for('users.logout') }}">Logout</a>
			{% else %}
				<a class="btn btn-primary d-lg-inline-block ms-5 me-3" id="login" href="{{ url_for('users.login') }}">Login</a>
			{% endif %}
		</div>
	</nav>

	<main>
		<br><br><br>
		{% with messages = get_flashed_messages(with_categories = true) %}
			{% if messages %}
				{% for category, message in messages %}
					<div class="alert alert-{{ category }} mt-4">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
		{% endwith %}

		{% block main %}{% endblock %}
	</main>
		
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-6 col-xs-12">
					<img class="d-flex justify-content-center" src="{{ url_for('static', filename='images/logo.png') }}" alt="logo">
				</div>
			
				<div class="col-md-4 col-sm-6 col-xs-12">
					<ul class="menu">
						<span>Menu</span>    
						<li>
							<a href="/home">Home</a>
						</li>
						<li>
							<a href="/about">About</a>
						</li>		
						<li>
							<a href="#">Blog</a>
						</li>
						<li>
							<a href="#">Gallery </a>
						</li>
					</ul>
				</div>
	
				<div class="col-md-4 col-sm-6 col-xs-12">
					<ul class="address">
						<span>Contact</span>       
						<li>
							<i class="fa fa-phone" aria-hidden="true"></i> <a href="#">Phone</a>
						</li>
						<li>
							<i class="fa fa-map-marker" aria-hidden="true"></i> <a href="#">Address</a>
						</li> 
						<li>
							<i class="fa fa-envelope" aria-hidden="true"></i> <a href="#">Email</a>
						</li> 
					</ul>
				</div>
			</div> 
		</div>
	</footer>
</body>
</html>

reazdonor/reazdonor/templates/login.html
{% extends "layout.html" %}

{% block main %}
	<section>
		<div class="container mt-5">
			<h1>Sign In</h1>
			<form method="POST" action="" class="form-control">
				{{ form.hidden_tag() }}

				<div class="col-12">
					{{ form.email.label(class = "form-label") }}
				
					{% if form.email.errors %}
						{{ form.email(class = "form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class = "form-control") }}
					{% endif %}
				</div>

				<div class="col-12">
					{{ form.password.label(class = "form-label mt-2") }}
				
					{% if form.password.errors %}
						{{ form.password(class = "form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class = "form-control") }}
					{% endif %}
				</div>

				<div class="col-12 mt-2">
					<div class="form-check">
						{% if form.remember_me.errors %}
							{{ form.remember_me(class = "form-check-input is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.remember_me.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.remember_me(class = "form-check-input") }}
						{% endif %}

						{{ form.remember_me.label(class = "form-check-label") }}
					</div>
				</div>

				<div class="col-md-6 mt-2">
					{{ form.submit(class = "btn btn-primary") }}
				</div>

				<br>
				<div class="col-12 mt-2">
					<small class="text-muted">Forgot password? <a href="{{ url_for('users.request_reset') }}">Click here</a></small>
				</div>

				<div class="col-12 mt-2">
					<small class="text-muted">Don't have an account? <a href="{{ url_for('users.signup') }}">Click here</a> to get started</small>
				</div>
			</form>
		</div>
	</section>
{% endblock main %}

reazdonor/reazdonor/templates/org_home.html
{% extends "layout.html" %}

{% block main %}		
	<section class="py-5 my-5">
		<div class="container">
			<h1 class="mb-5">{{ org.organization_name }}</h1>

			<div class="bg-white shadow rounded-lg d-block d-sm-flex">
				<div class="p-4">
					<div class="img-circle text-center mb-3">
						<img src="{{ url_for('static', filename = 'images/profiles/' + org.logo) }}" width="200px" height="200px" alt="Image" class="shadow">
					</div>

					<div>
						<h5 class="text-center mb-3">{{ org.email }}</h5>

						<p class="lead text-center">{{ org.address }}</p>
						{% if org.address2 == "" %}
							<p class="lead text-center">{{ org.address2 }}</p>
						{% endif %}
						<p class="lead text-center">{{ org.city }}, {{ org.state }}</p>
						<p class="lead text-center">({{ org.phone[:3] }}) {{ org.phone[3:6] }}-{{ org.phone[6:] }}</p>
					</div>
				</div>
					
				<div class="p-4 p-md-5" style="width: 100%;">
					<div class="container">
						<div class="d-flex justify-content-end">
							<div>
								<a class="btn btn-primary d-lg-inline-block" id="donate" href="{{ url_for('main.donate', org_id = org.id) }}">Donate</a>
							</div>
						</div>
						
						<div>
							<h4>Impact</h4>
							<p class="lead">{{ org.impact }}</p>
							<h4>Mission</h4>
							<p class="lead">{{ org.mission }}</p>
						</div>
					</div>
				</div>
			</div>		
		</div>
	</section>
{% endblock main %}